// Placeholder firebase options file.
// Normally generated by the FlutterFire CLI. Present as a stub
// so static analysis and simple runs don't fail when the
// generated file is not available during CI or local edits.
